// <auto-generated />
using System;
using HeroService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeroService.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629161336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VersionName")
                        .HasColumnType("text");

                    b.Property<string>("VersionNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameVersions");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Affiliations.Classifications.MythologyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MythologyTypes");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Affiliations.Classifications.OriginArchetype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OriginArchetypes");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Affiliations.Classifications.OriginCulture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OriginCultures");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Core.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("HeroClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HeroClassId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Core.HeroBaseStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("BaseAbilityPower")
                        .HasColumnType("real");

                    b.Property<float>("BaseArmor")
                        .HasColumnType("real");

                    b.Property<float>("BaseAttackDamage")
                        .HasColumnType("real");

                    b.Property<float>("BaseAttackRange")
                        .HasColumnType("real");

                    b.Property<float>("BaseAttackSpeed")
                        .HasColumnType("real");

                    b.Property<float>("BaseCastSpeed")
                        .HasColumnType("real");

                    b.Property<float>("BaseCooldownReduction")
                        .HasColumnType("real");

                    b.Property<float>("BaseCritChance")
                        .HasColumnType("real");

                    b.Property<float>("BaseCritDamageMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("BaseDamageReduction")
                        .HasColumnType("real");

                    b.Property<float>("BaseHealth")
                        .HasColumnType("real");

                    b.Property<float>("BaseMagicResistance")
                        .HasColumnType("real");

                    b.Property<float>("BaseMana")
                        .HasColumnType("real");

                    b.Property<float>("BaseMovementSpeed")
                        .HasColumnType("real");

                    b.Property<float>("BaseResourceRegeneration")
                        .HasColumnType("real");

                    b.Property<float>("BaseShieldStrengthMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HeroId")
                        .IsUnique();

                    b.ToTable("HeroBaseStats");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Core.HeroClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HeroClasses");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Core.HeroLore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundStory")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HeroLore");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Progression.HeroProgressionModifiers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AbilityPowerPerLevel")
                        .HasColumnType("real");

                    b.Property<float>("ArmorPerLevel")
                        .HasColumnType("real");

                    b.Property<float>("AttackDamagePerLevel")
                        .HasColumnType("real");

                    b.Property<float>("AttackSpeedPerLevel")
                        .HasColumnType("real");

                    b.Property<float>("CastSpeedPerLevel")
                        .HasColumnType("real");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<float>("HealthPerLevel")
                        .HasColumnType("real");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("MagicResistancePerLevel")
                        .HasColumnType("real");

                    b.Property<float>("ManaPerLevel")
                        .HasColumnType("real");

                    b.Property<float>("ResourceRegenerationPerLevel")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("HeroProgressionModifiers");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SkillType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Skills.SkillBaseStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("BaseCastTime")
                        .HasColumnType("real");

                    b.Property<float?>("BaseChannelDuration")
                        .HasColumnType("real");

                    b.Property<float?>("BaseCooldown")
                        .HasColumnType("real");

                    b.Property<float?>("BaseCrowdControlDuration")
                        .HasColumnType("real");

                    b.Property<float?>("BaseDamage")
                        .HasColumnType("real");

                    b.Property<float?>("BaseHealing")
                        .HasColumnType("real");

                    b.Property<float?>("BaseManaCost")
                        .HasColumnType("real");

                    b.Property<float?>("BaseRange")
                        .HasColumnType("real");

                    b.Property<float?>("BaseShieldValue")
                        .HasColumnType("real");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkillId")
                        .IsUnique();

                    b.ToTable("SkillBaseStats");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Skills.SkillEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("AbilityPowerRatio")
                        .HasColumnType("real");

                    b.Property<float?>("AttackDamageRatio")
                        .HasColumnType("real");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<int>("EffectType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChannelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInstant")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPeriodic")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Magnitude")
                        .HasColumnType("real");

                    b.Property<float?>("MaxHealthRatio")
                        .HasColumnType("real");

                    b.Property<int>("MaxStacks")
                        .HasColumnType("integer");

                    b.Property<float>("Radius")
                        .HasColumnType("real");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<int>("StackType")
                        .HasColumnType("integer");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillEffects");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Skills.SkillLore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisualExplanation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SkillLore");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Skills.SkillScalingModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AbilityPowerRatio")
                        .HasColumnType("real");

                    b.Property<float>("AttackDamageRatio")
                        .HasColumnType("real");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("MaxHealthRatio")
                        .HasColumnType("real");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SkillScalingModifiers");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Versioned.GameVersion.Modifiers.HeroModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("AbilityPowerMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("ArmorMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("AttackDamageMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("AttackRangeMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("AttackSpeedMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("CastSpeedMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("CooldownReductionMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("CritChanceMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("CritDamageMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("DamageReductionMultiplier")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("GameVersionId")
                        .HasColumnType("uuid");

                    b.Property<float?>("HealthMultiplier")
                        .HasColumnType("real");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("MagicResistanceMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("ManaMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("MovementSpeedMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("ResourceRegenerationMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("ShieldStrengthMultiplier")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("HeroModifiers");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Versioned.GameVersion.Modifiers.SkillModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("CastTimeMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("ChannelDurationMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("CooldownMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("CrowdControlDurationMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("DamageMultiplier")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("GameVersionId")
                        .HasColumnType("uuid");

                    b.Property<float>("HealingMultiplier")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("ManaCostMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("RangeMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("ShieldMultiplier")
                        .HasColumnType("real");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SkillModifiers");
                });

            modelBuilder.Entity("HeroService.Domain.Skins.Skin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<string>("SfxBundleKey")
                        .HasColumnType("text");

                    b.Property<string>("VfxBundleKey")
                        .HasColumnType("text");

                    b.Property<string>("VisualTheme")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skins");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Core.Hero", b =>
                {
                    b.HasOne("HeroService.Domain.Heroes.Core.HeroClass", "HeroClass")
                        .WithMany()
                        .HasForeignKey("HeroClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeroAffiliation", "Affiliation", b1 =>
                        {
                            b1.Property<Guid>("HeroId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ArchetypeId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MythologyId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("OriginCultureId")
                                .HasColumnType("uuid");

                            b1.HasKey("HeroId");

                            b1.HasIndex("ArchetypeId");

                            b1.HasIndex("MythologyId");

                            b1.HasIndex("OriginCultureId");

                            b1.ToTable("Heroes");

                            b1.HasOne("HeroService.Domain.Heroes.Affiliations.Classifications.OriginArchetype", "Archetype")
                                .WithMany()
                                .HasForeignKey("ArchetypeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("HeroId");

                            b1.HasOne("HeroService.Domain.Heroes.Affiliations.Classifications.MythologyType", "Mythology")
                                .WithMany()
                                .HasForeignKey("MythologyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasOne("HeroService.Domain.Heroes.Affiliations.Classifications.OriginCulture", "OriginCulture")
                                .WithMany()
                                .HasForeignKey("OriginCultureId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Archetype");

                            b1.Navigation("Mythology");

                            b1.Navigation("OriginCulture");
                        });

                    b.OwnsOne("HeroService.Domain.Heroes.Core.Skills.HeroSkillKit", "SkillKit", b1 =>
                        {
                            b1.Property<Guid>("HeroId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PassiveSkillId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PrimarySkillId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SecondarySkillId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TertiarySkillId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UltimateSkillId")
                                .HasColumnType("uuid");

                            b1.HasKey("HeroId");

                            b1.ToTable("Heroes");

                            b1.WithOwner()
                                .HasForeignKey("HeroId");
                        });

                    b.Navigation("Affiliation");

                    b.Navigation("HeroClass");

                    b.Navigation("SkillKit");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Core.HeroBaseStats", b =>
                {
                    b.HasOne("HeroService.Domain.Heroes.Core.Hero", null)
                        .WithOne("BaseStats")
                        .HasForeignKey("HeroService.Domain.Heroes.Core.HeroBaseStats", "HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Skills.SkillBaseStats", b =>
                {
                    b.HasOne("HeroService.Domain.Heroes.Skills.Skill", null)
                        .WithOne("BaseStats")
                        .HasForeignKey("HeroService.Domain.Heroes.Skills.SkillBaseStats", "SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Skills.SkillEffect", b =>
                {
                    b.HasOne("HeroService.Domain.Heroes.Skills.Skill", null)
                        .WithMany("Effects")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Core.Hero", b =>
                {
                    b.Navigation("BaseStats");
                });

            modelBuilder.Entity("HeroService.Domain.Heroes.Skills.Skill", b =>
                {
                    b.Navigation("BaseStats");

                    b.Navigation("Effects");
                });
#pragma warning restore 612, 618
        }
    }
}
