<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../../common.targets" />


  <ItemGroup>
	 
	  <PackageReference Include="Franz.Common.Caching" />
	 
	  <PackageReference Include="Franz.Common.EntityFramework" />
	 
	  <PackageReference Include="Franz.Common.EntityFramework.PostGres" />
	 
	  <PackageReference Include="Franz.Common.Hosting" />
	 
	  <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
	  
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HeroService.Contracts\HeroService.Contracts.csproj" />
    <ProjectReference Include="..\HeroService.Domain\HeroService.Domain.csproj" />
  </ItemGroup>

</Project>
